using Common.DTOs;
using Common.Entities;

namespace Services.Mappers
{
    internal static class UserMapper
    {
        public static User ToEntity(Common.DTOs.UserCreateUpdateDTO dto)
        {
            return new User
            {
                // Do not set UserPK here; it is generated by the database.
                UserName = dto.UserName,
                Email = dto.Email,
                Password = dto.Password,
                ActiveStatus = dto.ActiveStatus,
                RoleTypePK = dto.RoleTypePK,
                RoleName = string.Empty,
                FirstName = dto.FirstName,
                SecondName = dto.LastName,
                BirthDate = dto.BirthDate
            };
        }

        public static void ApplyUpdate(User entity, Common.DTOs.UserCreateUpdateDTO dto)
        {
            entity.UserName = dto.UserName;
            entity.Email = dto.Email;
            entity.Password = dto.Password;
            entity.ActiveStatus = dto.ActiveStatus;
            entity.RoleTypePK = dto.RoleTypePK;
            entity.FirstName = dto.FirstName;
            entity.SecondName = dto.LastName;
            entity.BirthDate = dto.BirthDate;
        }

        public static UserDTO ToDto(User user)
        {
            return new UserDTO
            {
                UserPK = user.UserPK,
                UserName = user.UserName,
                Email = user.Email,
                ActiveStatus = user.ActiveStatus,
                RoleName = user.RoleName,
                RoleTypePK = user.RoleTypePK,
                FirstName = user.FirstName,
                LastName = user.SecondName,
                BirthDate = user.BirthDate
            };
        }
    }
}
