<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="4.7.0" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Common\Common.csproj" />
	<ProjectReference Include="..\BusinessLogic\BusinessLogic.csproj" />
  </ItemGroup>

</Project>
