CREATE TABLE RoleTypes (
	RoleTypePK UNIQUEIDENTIFIER NOT NULL,
	RoleName VARCHAR(50) NOT NULL,

	CONSTRAINT PK_RoleTypes PRIMARY KEY NONCLUSTERED (RoleTypePK)
);
GO

CREATE TABLE Users (
	UserPK UNIQUEIDENTIFIER NOT NULL,
	UserName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	ActiveStatus BIT NOT NULL,
	RoleTypePK UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT PK_Users PRIMARY KEY NONCLUSTERED (UserPK),
	CONSTRAINT FK_Users_RoleTypes FOREIGN KEY (RoleTypePK)
		REFERENCES RoleTypes(RoleTypePK),
	CONSTRAINT UQ_Users_UserName UNIQUE (UserName),
	CONSTRAINT UQ_Users_Email UNIQUE (Email)
);
GO

CREATE TABLE UserData (
	UserPK UNIQUEIDENTIFIER NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	SecondName NVARCHAR(50) NULL,
	BirthDate DATETIME2(7) NULL,

	CONSTRAINT PK_UserData PRIMARY KEY NONCLUSTERED (UserPK),
	CONSTRAINT FK_UserData_Users FOREIGN KEY (UserPK)
		REFERENCES Users(UserPK)
);
GO