CREATE TABLE RoleTypes (
	RoleTypePK TINYINT IDENTITY(1,1) NOT NULL,

	CONSTRAINT PK_RoleTypes PRIMARY KEY (RoleTypePK)
);

CREATE TABLE Users (
	UserPK INT IDENTITY(1,1) NOT NULL,
	UserName VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	ActiveStatus BIT NOT NULL,
	RoleTypePK TINYINT NOT NULL,

	CONSTRAINT PK_Users PRIMARY KEY (UserPK),
	CONSTRAINT FK_Users_RoleTypes FOREIGN KEY (RoleTypePK) 
		REFERENCES RoleTypes(RoleTypePK)
);

CREATE TABLE UserData (
	UserPK INT NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	SecondName VARCHAR(50) NULL,
	BirthDate DATATIME2(7) NULL,

	CONSTRAINT PK_UserData PRIMARY KEY (UserPK),
	CONSTRAINT FK_UserData_Users FOREIGN KEY (UserPK) 
		REFERENCES Users(UserPK)
);
