CREATE PROCEDURE dbo.Users_DEL
	@UserPK UNIQUEIDENTIFIER
AS
BEGIN
	SET NOCOUNT ON;

	BEGIN TRANSACTION;
	BEGIN TRY
		DELETE FROM dbo.UserData
		WHERE UserPK = @UserPK;

		DELETE FROM dbo.Users
		WHERE UserPK = @UserPK;

		COMMIT TRANSACTION;
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
		THROW;
	END CATCH
END;
GO
